# Generated by Django 5.0.3 on 2025-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Chat histories'},
        ),
    ]
